inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  TargetRubyVersion: 3.1.4
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/**/*
    - config.ru
    - Rakefile

Layout/EndAlignment:
  AutoCorrect: true

Layout/IndentationWidth:
  Width: 2

Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  AutoCorrect: true

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "#consistent-string-literals"
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Layout/LineLength:
  Description: "Checks that line length does not exceed the configured limit."
  Max: 100
  AutoCorrect: true
  Exclude:
    - Gemfile

Bundler/OrderedGems:
  Description: >-
    Gems within groups in the Gemfile should be alphabetically sorted.
  Enabled: true
  ConsiderPunctuation: true
