default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: gym_pro_development

test:
  <<: *default
  database: gym_pro_test

production:
  primary: &primary_production
    <<: *default
    database: gym_pro_production
    username: gym_pro
    password: <%= ENV["GYM_PRO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: gym_pro_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: gym_pro_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: gym_pro_production_cable
    migrations_paths: db/cable_migrate
